plugins {
    id 'java'
    id 'checkstyle'
    id 'pmd'
    id 'jacoco'
    id 'com.diffplug.spotless' version '8.0.0'
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Root project depends on the game module
    implementation project(':game')
}

test {
  useJUnitPlatform()
  reports {
    junitXml.required = true; html.required = true
  }
}

application {
    mainClass = 'avengers.core.Game'
}
