name: Release
on:
    push:
        tags: [ 'v*.*.*' ]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: '21'
            - uses: gradle/actions/setup-gradle@v3
            - run: ./gradlew clean jar --no-daemon
            - uses: softprops/action-gh-release@v2
              with:
                  files: build/libs/*.jar
